version: "3.8"
services:
  web:
    container_name: sirka-landing
    image: 218649523932.dkr.ecr.ap-southeast-1.amazonaws.com/sirka-landing:${DOCKER_IMAGE_TAG}
    ports:
      - "80:3000"
    env_file:
      - .env
